version: '3'
services:
  java-srv:
    build: py-srv
    command: sh -c "/wait && python app.py"
    environment:
      - WAIT_HOSTS=db:8529
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30

  db:
    # undocumented image that allows 32 bit CPU
    image: arangodb/arangodb:3.9.2-noavx
    environment:
      - ARANGO_ROOT_PASSWORD=pass
    ports:
      - 8529
